### ISSUE TITLE
✨ This needs a demo ✨

### ISSUE THREAD

**Issue by mischah** [bullgit/promise-promise#1]
Hej, I think this needs a demo to showcase its awesomeness. 

I’m just not sure how to demo this.
Just a link to a JS Bin?
An animated gif taken from the node REPL?

Anyone with a good idea?

@bullgit/gitches

**Comment by KevinGimbel** [comment]
@mischah Both IMO. One or more JSbin(s) as well as a gif (preferable in crappy quality). Cool Turbo project! 😍

**Comment by reneviering** [comment]
Hey,

yeah you are both right! :) A demo would be awesome. What do you think about a github page where I wrap an AJAX-Request (GET: https://bullg.it/members.json). If it succeeds, I show the member JSON. Otherwise I show the returned excuse highlighted in red to indicate that the promise was rejected!? You can repeat it by pressing a »Try to load gitches« button. !?

**Comment by KevinGimbel** [comment]
@revrng sounds good to me!

**Comment by mischah** [comment]
:+1:

**Comment by reneviering** [comment]
Hey,

I added a little demo page: https://bullg.it/promise-promise

@mischah can I close this issue?

**Comment by Haroenv** [comment]
Can be closed! 💯
